from typing import Dict

# use hash map to store the count of each nucleotide
# iterate through the DNA sequence and increment the count of each nucleotide
# return the hash map
# TC: O(N), SC: O(1) since the hash map will always have 4 keys
def count_nucleotides(dna_sequence: str) -> Dict:
    """
    Count the number of each nucleotide in a DNA sequence.
    """
    nucleotide_count = {'A': 0, 'C': 0, 'G': 0, 'T': 0}
    for nucleotide in dna_sequence:
        nucleotide_count[nucleotide] += 1
    return nucleotide_count

def test_count_nucleotides():
    dna_sequence = "TGCGGTGTGTGCCTTCAGCTCGCCGCTCTAAAGCATTCGGAACACATGTTGACGCGACCCGCGCATTCAGGCACGGTTGGCATGCGAGAGCAATATGCAGTACTTTATTGATGAGTGTATTGTAAAAAACAAGTGCAACTCTTAAGCATCGATGCGCAGTGGTACAATAGGTTGTAGGGCTCGAAGTTCGCCGCCCAGTTCAAACCGTTTTAATGACATACCCACGAGCGTGCGTTAACGATTGACGGTTTTAGCGCGAGCGGTGTATGGTAAGCGACCTTTACACGACCCTGCATGTTATAGTGCCATCATAAGGTAGGCCCTGTTATTTACACCTGATGACTCCTTGGCCTTATCGCGCAGGTAGTTCACTGGAACCTAGTTTGCCACGTTAATAGCAGCCAGGTCGCCCTACGAGGGGTCACGACTGCAGCGATGTGATGTAGTCAAGCAGGGTTTCGTAATATAACCATATCACGATTTTCGCCGCTTGTTCTTGCACCGTCACTTCAGCCGGTCCCAGCGTTTATTAATTTATCAATTGAAGAGTCCGCCATGCACGATCCTACGGAGGCTGAGCACGTCGACTCGAAGTGGAGTAGGGCCACTGATGAGATCGCCCATTCCCATGTTCGTTTAGCTCCTATTATCTTTGGAGCGCATAACCTATGGTCCTGTGAGACCAACCTTTTAAAATCTTGTACGGTTTTTGGTAAGGACTGAGTACGTTTTGGCAAATCTAGCCTGTCCCCGATGAATAGCACATGGAATGCTCGCCTGACTAAACGATTACTAAGTGAGCCTTCAGAAGTATGTCCAAGATCCCG"

    assert count_nucleotides(dna_sequence) == {'A': 199, 'C': 201, 'G': 204, 'T': 223}
    print("count_nucleotides PASSED")